	
default:	
	javac Client.java Config.java Controller.java ListenerSocket.java Message.java Server.java MaekawaCallable.java MaekawaProtocol.java CSRequest.java CSRequestComparator.java 
clean: 
	$(RM) *.class -f
	$(RM) logfile -f
